language: python

sudo: false

env:
  matrix:
    - VLUA="lua=5.4"
    - VLUA="lua=5.3"
    - VLUA="lua=5.2"
    - VLUA="lua=5.1"
    - VLUA="luajit=2.1"
    - VLUA="luajit=2.0"


before_install:
  - pip install git+https://github.com/luarocks/hererocks
  - hererocks here -r^ --$VLUA --patch
  - export PATH=$PWD/here/bin:$PATH lpath=$PWD/here/share/lua/${VLUA#lua=} lcpath=$PWD/here/lib/lua/${VLUA#lua=}


install:
  - luarocks install ldoc
  - luarocks install ansicolors
  - luarocks install specl
  - luarocks install typecheck
  - luarocks install luacov

script:
  - luarocks make --force LUA_INCDIR=$PWD/here/include
  - LUA_PATH="$lpath/?.lua;$lpath/?/init.lua" LUA_CPATH="$lcpath/?.so" lua -e 'for k,v in pairs(require"posix") do print(k,v) end'
  - LUA_PATH="$lpath/?.lua;$lpath/?/init.lua" LUA_CPATH="$lcpath/?.so" lua -e 'for k,v in pairs(require"posix._base") do print(k,v) end'
  - specl -vfreport --coverage spec/*_spec.yaml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f luacov.report.out

notifications:
  slack: aspirinc:JyWeNrIdS0J5nf2Pn2BS1cih
